class Lists {
    // "Cappy" = moons like Pops Out of the Tail
    // "Hat" = Hat-and-Seek moons
    // "Tourist" = not an Achievements, just for randomization
    // "Yoshi" = same as above (and why not all yoshi moons are tagged)
    // "Ach" = Achievements moon
    // "Story" = not an Achievements, just to force inclusion
    // "Multi" = not an Achievements, just for moon counting
    static final String[][] moons = {
            {"Frog-Jumping Above the Fog", "Cap", "false"},
            {"Frog-Jumping From the Top Deck", "Cap", "false"},
            {"Cap Kingdom Timer Challenge 1", "Cap", "false", "Timer"},
            {"Good Evening, Captain Toad", "Cap", "false", "Toad"},
            {"Shopping in Bonneton", "Cap", "false"},
            {"Skimming the Poison Tide", "Cap", "false"},
            {"Slipping Through the Poison Tide", "Cap", "false"},
            {"Push-Block Peril", "Cap", "false"},
            {"Hidden Among the Push-Blocks", "Cap", "false"},
            {"Searching the Frog Pond", "Cap", "false"},
            {"Secrets of the Frog Pond", "Cap", "false"},
            {"The Forgotten Treasure", "Cap", "false", "gp"},
            {"Taxi Flying Through Bonneton", "Cap", "false"},
            {"Bonneter Blockade", "Cap", "false"},
            {"Cap Kingdom Regular Cup", "Cap", "false", "kfr"},
            {"Peach in the Cap Kingdom", "Cap", "false", "Peach"},
            {"Found with Cap Kingdom Art", "Moon", "false", "Art", "gp"},
            {"Next to Glasses Bridge", "Cap", "false"},
            {"Danger Sign", "Cap", "false"},
            {"Under the Big One's Brim", "Cap", "false"},
            {"Fly to the Edge of the Fog", "Cap", "false"},
            {"Spin the Hat, Get a Prize", "Cap", "false"},
            {"Hidden in a Sunken Hat", "Cap", "false", "Cappy"},
            {"Fog Shrouded Platform", "Cap", "false", "gp"},
            {"Bird Traveling in the Fog", "Cap", "false", "Bird"},
            {"Caught Hopping Near the Ship!", "Cap", "false", "Mips"},
            {"Taking Notes: In the Fog", "Cap", "false", "Notes"},
            {"Cap Kingdom Timer Challenge 2", "Cap", "false", "Timer"},
            {"Cap Kingdom Master Cup", "Cap", "false", "kfr"},
            {"Roll On and On", "Cap", "false"},
            {"Precision Rolling", "Cap", "false"},
            {"Our First Power Moon", "Cascade", "true", "Story"},
            {"Multi Moon Atop the Falls", "Cascade", "true", "Story", "Multi"},
            {"Chomp Through the Rocks", "Cascade", "true"},
            {"Behind the Waterfall", "Cascade", "true", "8-bit"},
            {"On Top of the Rubble", "Cascade", "true"},
            {"Treasure of the Waterfall Basin", "Cascade", "true", "Chest"},
            {"Above a High Cliff", "Cascade", "true"},
            {"Across the Floating Isles", "Cascade", "true"},
            {"Cascade Kingdom Timer Challenge 1", "Cascade", "true", "Timer"},
            {"Cascade Kingdom Timer Challenge 2", "Cascade", "true", "Timer"},
            {"Good Morning, Captain Toad!", "Cascade", "true", "Toad"},
            {"Dinosaur Nest: Big Cleanup!", "Cascade", "true"},
            {"Dinosaur Nest: Running Wild!", "Cascade", "true"},
            {"Nice Shot with the Chain Chomp", "Cascade", "true"},
            {"Very Nice Shot with the Chain Chomp", "Cascade", "true"},
            {"Past the Chasm Lifts", "Cascade", "true"},
            {"Hidden Chasm Passage", "Cascade", "true", "8-bit"},
            {"Secret Path to Fossil Falls!", "Cascade", "false"},
            {"A Tourist in the Cascade Kingdom", "Cascade", "false", "Tourist", "2"},
            {"Rolling Rock by the Falls", "Cascade", "false"},
            {"Peach in the Cascade Kingdom", "Cascade", "false", "Peach"},
            {"Cascade Kingdom Regular Cup", "Cascade", "false", "kfr"},
            {"Caveman Cave-Fan", "Cascade", "false", "Outfit"},
            {"Shopping in Fossil Falls", "Cascade", "false"},
            {"Sphynx Traveling to the Waterfall", "Cascade", "false"},
            {"Bottom of the Waterfall Basin", "Cascade", "false", "gp"},
            {"Just a Hat, Skip, and a Jump", "Cascade", "false"},
            {"Treasure Under the Cliff", "Cascade", "false"},
            {"Next to Stone Arch", "Cascade", "false"},
            {"Guarded by a Colossal Fossil", "Cascade", "false", "Cappy"},
            {"Under the Old Electrical Pole", "Cascade", "false", "gp"},
            {"Under the Ground", "Cascade", "false", "gp"},
            {"Inside the Busted Fossil", "Cascade", "false"},
            {"Caught Hopping at the Waterfall!", "Cascade", "false", "Mips"},
            {"Taking Notes: Hurry Upward", "Cascade", "false", "Notes", "8-bit"},
            {"Cascade Kingdom Master Cup", "Cascade", "false", "kfr"},
            {"Across the Mysterious Clouds", "Cascade", "false"},
            {"Atop a Wall Among the Clouds", "Cascade", "false"},
            {"Across the Gusty Bridges", "Cascade", "false"},
            {"Flying Far Away from Gusty Bridges", "Cascade", "false"},
            {"Atop the Highest Tower", "Sand", "true"},
            {"Moon Shards in the Sand", "Sand", "true"},
            {"Showdown on the Inverted Pyramid", "Sand", "true", "Story", "Multi"},
            {"The Hole in the Desert", "Sand", "true", "Story", "Multi"},
            {"Overlooking the Desert Town", "Sand", "true"},
            {"Alcove in the Ruins", "Sand", "true"},
            {"On the Leaning Pillar", "Sand", "true"},
            {"Hidden Room in the Flowing Sands", "Sand", "true"},
            {"Secret of the Mural", "Sand", "true", "8-bit"},
            {"Secret of the Inverted Mural", "Sand", "true", "8-bit"},
            {"On Top of the Stone Archway", "Sand", "true"},
            {"From a Crate in the Ruins", "Sand", "true"},
            {"On the Statue's Tail", "Sand", "true", "Cappy"},
            {"Hang Your Hat on the Fountain", "Sand", "true", "Cappy"},
            {"Where the Birds Gather", "Sand", "true", "gp"},
            {"Top of a Dune", "Sand", "true", "gp"},
            {"Lost in the Luggage", "Sand", "true", "gp"},
            {"Bullet Bill Breakthrough", "Sand", "true"},
            {"Inside a Block Is a Hard Place", "Sand", "true"},
            {"Bird Traveling the Desert", "Sand", "true", "Bird"},
            {"Bird Traveling the Wastes", "Sand", "true", "Bird"},
            {"The Lurker Under the Stone", "Sand", "true", "gp"},
            {"The Treasure of Jaxi Ruins", "Sand", "true", "Chest"},
            {"Desert Gardening: Plaza Seed", "Sand", "true", "Seed"},
            {"Desert Gardening: Ruins Seed", "Sand", "true", "Seed"},
            {"Desert Gardening: Seed on the Cliff", "Sand", "true", "Seed"},
            {"Sand Kingdom Timer Challenge 1", "Sand", "true", "Timer"},
            {"Sand Kingdom Timer Challenge 2", "Sand", "true", "Timer"},
            {"Sand Kingdom Timer Challenge 3", "Sand", "true", "Timer"},
            {"Found in the Sand! Good Dog!", "Sand", "true", "gp"},
            {"Taking Notes: Jump on the Palm", "Sand", "true", "Notes"},
            {"Herding Sheep in the Dunes", "Sand", "true", "Sheep"},
            {"Fishing in the Oasis", "Sand", "true", "Fishing"},
            {"Love in the Heart of the Desert", "Sand", "true", "Goomba"},
            {"Among the Five Cactuses", "Sand", "true"},
            {"You're Quite a Catch, Captain Toad!", "Sand", "true", "Fishing", "Toad"},
            {"Jaxi Reunion!", "Sand", "true"},
            {"Welcome Back, Jaxi!", "Sand", "true"},
            {"Wandering Cactus", "Sand", "true"},
            {"Sand Quiz: Wonderful!", "Sand", "true", "Sphynx"},
            {"Shopping in Tostarena", "Sand", "true"},
            {"Employees Only", "Sand", "true"},
            {"Sand Kingdom Slots", "Sand", "true", "Slots"},
            {"Walking the Desert!", "Sand", "true", "Trace"},
            {"Hidden Room in the Inverted Pyramid", "Sand", "true", "Chest"},
            {"Underground Treasure Chest", "Sand", "true", "Chest"},
            {"Goomba Tower Assembly", "Sand", "true"},
            {"Under the Mummy's Curse", "Sand", "true"},
            {"Ice Cave Treasure", "Sand", "true"},
            {"Sphynx's Treasure Vault", "Sand", "true", "Chest"},
            {"A Rumble from the Sandy Floor", "Sand", "true", "gp"},
            {"Dancing with New Friends", "Sand", "true", "Outfit"},
            {"The Invisible Maze", "Sand", "true"},
            {"Skull Sign in the Transparent Maze", "Sand", "true", "Cappy"},
            {"The Bullet Bill Maze: Break Through!", "Sand", "true"},
            {"The Bullet Bill Maze: Side Path", "Sand", "true"},
            {"Jaxi Driver", "Sand", "true"},
            {"Jaxi Stunt Driving", "Sand", "true", "Notes"},
            {"Strange Neighborhood", "Sand", "true"},
            {"Above a Strange Neighborhood", "Sand", "true"},
            {"Secret Path to Tostarena!", "Sand", "false"},
            {"Found with Sand Kingdom Art", "Bowser's", "false", "Art", "gp"},
            {"Jammin' in the Sand Kingdom", "Sand", "false", "Music"},
            {"Hat-and-Seek: In the Sand", "Sand", "false", "Hat"},
            {"Sand Kingdom Regular Cup", "Sand", "false", "kfr"},
            {"Binding Band Returned", "Sand", "false", "gp"},
            {"'Round-the-World Tourist", "Sand", "false", "Tourist", "6"},
            {"Peach in the Sand Kingdom", "Sand", "false", "Peach"},
            {"Mighty Leap from the Palm Tree!", "Sand", "false"},
            {"On the North Pillar", "Sand", "false"},
            {"Into the Flowing Sands", "Sand", "false"},
            {"In the Skies Above the Canyon", "Sand", "false"},
            {"Island in the Poison Swamp", "Sand", "false"},
            {"An Invisible Gleam", "Sand", "false", "gp"},
            {"On the Eastern Pillar", "Sand", "false"},
            {"Caught Hopping in the Desert!", "Sand", "false", "Mips"},
            {"Poster Cleanup", "Sand", "false"},
            {"Taking Notes: Running Down", "Sand", "false", "Notes"},
            {"Taking Notes: In the Wall Painting", "Sand", "false", "8-bit", "Notes"},
            {"Love at the Edge of the Desert", "Sand", "false", "Goomba"},
            {"More Walking in the Desert!", "Sand", "false", "Trace"},
            {"Sand Kingdom Master Cup", "Sand", "false", "kfr"},
            {"Where the Transparent Platforms End", "Sand", "false"},
            {"Jump Onto the Transparent Lift", "Sand", "false"},
            {"Colossal Ruins: Dash! Jump!", "Sand", "false"},
            {"Sinking Colossal Ruins: Hurry!", "Sand", "false"},
            {"Through the Freezing Waterway", "Sand", "false"},
            {"Freezing Waterway: Hidden Room", "Sand", "false"},
            {"Broodals Over the Lake", "Lake", "true", "Story", "Multi"},
            {"Dorrie-Back Rider", "Lake", "true"},
            {"Cheep Cheep Crossing", "Lake", "true"},
            {"End of the Hidden Passage", "Lake", "true"},
            {"What's in the Box?", "Lake", "true"},
            {"On the Lakeshore", "Lake", "true"},
            {"From the Broken Pillar", "Lake", "true", "gp"},
            {"Treasure in the Spiky Waterway", "Lake", "true", "Chest"},
            {"Lake Gardening: Spiky Passage Seed", "Lake", "true", "Seed"},
            {"Lake Kingdom Timer Challenge 1", "Lake", "true", "Timer"},
            {"Lake Kingdom Timer Challenge 2", "Lake", "true", "Timer"},
            {"Moon Shards in the Lake", "Lake", "true"},
            {"Taking Notes: Dive and Swim", "Lake", "true", "Notes"},
            {"Taking Notes: In the Cliffside", "Lake", "true", "8-bit", "Notes"},
            {"Lake Fishing", "Lake", "true", "Fishing"},
            {"I Met a Lake Cheep Cheep!", "Lake", "true"},
            {"Our Secret Little Room", "Lake", "true"},
            {"Let's Go Swimming, Captain Toad!", "Lake", "true", "Toad"},
            {"Shopping in Lake Lamode", "Lake", "true"},
            {"A Successful Repair Job", "Lake", "true"},
            {"I Feel Underdressed", "Lake", "true", "Cappy", "Outfit"},
            {"Unzip the Chasm", "Lake", "true"},
            {"Super-Secret Zipper", "Lake", "true"},
            {"Jump, Grab, Cling, and Climb", "Lake", "true"},
            {"Jump, Grab, and Climb Some More", "Lake", "true", "Chest"},
            {"Secret Path to Lake Lamode!", "Lake", "false", "Chest"},
            {"Found with Lake Kingdom Art", "Cascade", "false", "Art", "gp"},
            {"Taxi Flying Through Lake Lamode", "Lake", "false"},
            {"That Trendy \"Pirate\" Look", "Lake", "false", "Outfit"},
            {"Space Is \"In\" Right Now", "Lake", "false", "Outfit"},
            {"That \"Old West\" Style", "Lake", "false", "Outfit"},
            {"Lake Kingdom Regular Cup", "Lake", "false", "kfr"},
            {"Peach in the Lake Kingdom", "Lake", "false", "Peach"},
            {"Behind the Floodgate", "Lake", "false"},
            {"High-Flying Leap", "Lake", "false"},
            {"Deep, Deep Down", "Lake", "false"},
            {"Rooftop of the Water Plaza", "Lake", "false", "gp"},
            {"Bird Traveling Over the Lake", "Lake", "false", "Bird"},
            {"Love by the Lake", "Lake", "false", "Goomba"},
            {"Lake Kingdom Master Cup", "Lake", "false", "kfr"},
            {"Waves of Poison: Hoppin' Over", "Lake", "false"},
            {"Waves of Poison: Hop to It!", "Lake", "false"},
            {"Road to Sky Garden", "Wooded", "true", "Story"},
            {"Flower Thieves of Sky Garden", "Wooded", "true", "Story", "Multi"},
            {"Path to the Secret Flower Field", "Wooded", "true", "Story"},
            {"Defend the Secret Flower Field!", "Wooded", "true", "Story", "Multi"},
            {"Behind the Rock Wall", "Wooded", "true"},
            {"Back Way Up the Mountain", "Wooded", "true", "8-bit"},
            {"Rolling Rock in the Woods", "Wooded", "true"},
            {"Caught Hopping in the Forest!", "Wooded", "true", "Mips"},
            {"Thanks for the Charge!", "Wooded", "true", "gp"},
            {"Atop the Tall Tree", "Wooded", "true"},
            {"Tucked Away Inside the Tunnel", "Wooded", "true"},
            {"Over the Cliff's Edge", "Wooded", "true"},
            {"The Nut 'Round the Corner", "Wooded", "true"},
            {"Climb the Cliff to Get the Nut", "Wooded", "true"},
            {"The Nut in the Red Maze", "Wooded", "true"},
            {"The Nut at the Dead End", "Wooded", "true"},
            {"Cracked Nut on a Crumbling Tower", "Wooded", "true"},
            {"The Nut that Grew on the Tall Fence", "Wooded", "true"},
            {"Fire in the Cave", "Wooded", "true"},
            {"Hey Out There, Captain Toad!", "Wooded", "true", "Toad"},
            {"Love in the Forest Ruins", "Wooded", "true", "Goomba"},
            {"Inside a Rock in the Forest", "Wooded", "true"},
            {"Shopping in Steam Gardens", "Wooded", "true"},
            {"Nut Planted in the Tower", "Wooded", "true"},
            {"Stretching Your Legs", "Wooded", "true"},
            {"Spinning-Platforms Treasure", "Wooded", "true"},
            {"Make the Secret Flower Field Bloom", "Wooded", "true"},
            {"Rolling Rock in the Deep Woods", "Wooded", "true"},
            {"Glowing in the Deep Woods", "Wooded", "true", "Timer"},
            {"Past the Peculiar Pipes", "Wooded", "true"},
            {"By the Babbling Brook in Deep Woods", "Wooded", "true", "gp"},
            {"The Hard Rock in Deep Woods", "Wooded", "true", "gp"},
            {"A Treasure Made from Coins", "Wooded", "true"},
            {"Beneath the Roots of the Moving Tree", "Wooded", "true", "gp"},
            {"Deep Woods Treasure Trap", "Wooded", "true", "Chest"},
            {"Exploring for Treasure", "Wooded", "true", "Outfit", "Chest"},
            {"Wooded Kingdom Timer Challenge 1", "Wooded", "true", "Timer"},
            {"Wooded Kingdom Timer Challenge 2", "Wooded", "true", "Timer"},
            {"Flooding Pipeway", "Wooded", "true"},
            {"Flooding Pipeway Ceiling Secret", "Wooded", "true"},
            {"Wandering in the Fog", "Wooded", "true"},
            {"Nut Hidden in the Fog", "Wooded", "true"},
            {"Flower Road Run", "Wooded", "true"},
            {"Flower Road Reach", "Wooded", "true"},
            {"Elevator Escalation", "Wooded", "true"},
            {"Elevator Blind Spot", "Wooded", "true"},
            {"Walking on Clouds", "Wooded", "true"},
            {"Above the Clouds", "Wooded", "true"},
            {"Secret Path to the Steam Gardens!", "Wooded", "false"},
            {"Found with Wooded Kingdom Art", "Sand", "false", "Art", "gp"},
            {"Swing Around Secret Flower Field", "Wooded", "false"},
            {"Jammin' in the Wooded Kingdom", "Wooded", "false", "Music"},
            {"Wooded Kingdom Regular Cup", "Wooded", "false", "kfr"},
            {"Peach in the Wooded Kingdom", "Wooded", "false", "Peach"},
            {"High Up in the Cave", "Wooded", "false"},
            {"Lost in the Tall Trees", "Wooded", "false"},
            {"Looking Down on the Goombas", "Wooded", "false"},
            {"High Up on a Rock Wall", "Wooded", "false"},
            {"The Nut in the Robot Storeroom", "Wooded", "false"},
            {"Above the Iron Mountain Path", "Wooded", "false"},
            {"The Nut Under the Observation Deck", "Wooded", "false"},
            {"Bird Traveling the Forest", "Wooded", "false", "Bird"},
            {"Invader in the Sky Garden", "Wooded", "false"},
            {"Hot, Hot, Hot from the Campfire", "Wooded", "false"},
            {"Wooded Kingdom Timer Challenge 3", "Wooded", "false", "Timer"},
            {"Moon Shards in the Forest", "Wooded", "false"},
            {"Taking Notes: On Top of the Wall", "Wooded", "false", "Notes"},
            {"Taking Notes: Stretching", "Wooded", "false", "Notes"},
            {"Wooded Kingdom Master Cup", "Wooded", "false", "kfr"},
            {"I Met an Uproot!", "Wooded", "false"},
            {"Invisible Road: Danger!", "Wooded", "false"},
            {"Invisible Road: Hidden Room", "Wooded", "false", "Chest"},
            {"Herding Sheep Above the Forest Fog", "Wooded", "false", "Sheep"},
            {"Herding Sheep on the Iron Bridge", "Wooded", "false", "Sheep"},
            {"Down and Back Breakdown Road", "Wooded", "false"},
            {"Below Breakdown Road", "Wooded", "false"},
            {"Picture Match: Basically a Goomba", "Cloud", "false"},
            {"Peach in the Cloud Kingdom", "Cloud", "false", "Peach"},
            {"Digging in the...Cloud?", "Cloud", "false", "gp"},
            {"High, High Above the Clouds", "Cloud", "false"},
            {"Crossing the Cloud Sea", "Cloud", "false"},
            {"Taking Notes: Up and Down", "Cloud", "false", "Notes"},
            {"Picture Match: A Stellar Goomba!", "Cloud", "false"},
            {"King of the Cube!", "Cloud", "false"},
            {"The Sixth Face", "Cloud", "false", "8-bit"},
            {"Atop a Propeller Pillar", "Lost", "true"},
            {"Below the Cliff's Edge", "Lost", "true"},
            {"Inside the Stone Cage", "Lost", "true"},
            {"On a Tree in the Swamp", "Lost", "true"},
            {"Over the Fuzzies, Above the Swamp", "Lost", "true"},
            {"Avoiding Fuzzies Inside the Wall", "Lost", "true", "8-bit"},
            {"Inside the Rising Stone Pillar", "Lost", "true"},
            {"Enjoying the View of Forgotten Isle", "Lost", "true"},
            {"On the Mountain Road", "Lost", "true", "gp"},
            {"A Propeller Pillar's Secret", "Lost", "true", "gp"},
            {"Wrecked Rock Block", "Lost", "true"},
            {"A Butterfly's Treasure", "Lost", "true", "Bird"},
            {"Caught Hopping in the Jungle!", "Lost", "false", "Mips"},
            {"Cave Gardening", "Lost", "true"},
            {"Moon Shards in the Jungle", "Lost", "true"},
            {"Peeking Out from Under the Bridge", "Lost", "true"},
            {"Twist 'n' Turn-Up Treasure", "Lost", "true"},
            {"Soaring Over Forgotten Isle!", "Lost", "true"},
            {"The Caged Gold", "Lost", "true"},
            {"Get Some Rest, Captain Toad!", "Lost", "true", "Toad"},
            {"Shopping on Forgotten Isle", "Lost", "true"},
            {"Taxi Flying Through Forgotten Isle", "Lost", "false"},
            {"I Met a Tropical Wiggler!", "Lost", "false"},
            {"Lost Kingdom Regular Cup", "Lost", "false", "kfr"},
            {"Peach in the Lost Kingdom", "Lost", "false", "Peach"},
            {"The Shining Fruit", "Lost", "false"},
            {"Jump Down to the Top of a Tree", "Lost", "false"},
            {"Line It Up, Blow It Up", "Lost", "false"},
            {"Taking Notes: Stretch and Shrink", "Lost", "false", "Notes"},
            {"Lost Kingdom Master Cup", "Lost", "false", "kfr"},
            {"Lost Kingdom Timer Challenge", "Lost", "false", "Timer"},
            {"Stretch and Traverse the Jungle", "Lost", "false"},
            {"Aglow in the Jungle", "Lost", "false"},
            {"Chasing Klepto", "Lost", "false"},
            {"Extremely Hot Bath", "Lost", "false"},
            {"New Donk City's Pest Problem", "Metro", "true", "Story", "Multi"},
            {"Drummer on Board!", "Metro", "true", "Story"},
            {"Guitarist on Board!", "Metro", "true", "Story"},
            {"Bassist on Board!", "Metro", "true", "Story"},
            {"Trumpeter on Board!", "Metro", "true", "Story"},
            {"Powering Up the Station", "Metro", "true", "Story"},
            {"A Traditional Festival!", "Metro", "true", "Story", "Multi"},
            {"Inside an Iron Girder", "Metro", "true"},
            {"Swaying in the Breeze", "Metro", "true"},
            {"Girder Sandwich", "Metro", "true"},
            {"Glittering Above the Pool", "Metro", "true"},
            {"Dizzying Heights", "Metro", "true"},
            {"Secret Girder Tunnel!", "Metro", "true"},
            {"Who Piled Garbage on This?", "Metro", "true", "gp"},
            {"Hidden in the Scrap", "Metro", "true", "gp"},
            {"Left at the Cafe?", "Metro", "true", "gp"},
            {"Caught Hopping on a Building!", "Metro", "true", "Mips"},
            {"How Do They Take Out the Trash?", "Metro", "true"},
            {"Metro Kingdom Timer Challenge 1", "Metro", "true", "Timer"},
            {"Metro Kingdom Timer Challenge 2", "Metro", "true", "Timer"},
            {"City Gardening: Building Planter", "Metro", "false", "Seed"},
            {"City Gardening: Plaza Planter", "Metro", "false", "Seed"},
            {"City Gardening: Rooftop Planter", "Metro", "false", "Seed"},
            {"How You Doin', Captain Toad?", "Metro", "true", "Toad"},
            {"Free Parking: Rooftop Hop", "Metro", "true"},
            {"Bench Friends", "Metro", "true"},
            {"Shopping in New Donk City", "Metro", "true"},
            {"Metro Kingdom Slots", "Metro", "true", "Slots"},
            {"Jump-Rope Hero", "Metro", "true", "Jumprope"},
            {"Jump-Rope Genius", "Metro", "true", "Jumprope"},
            {"Remotely Captured Car", "Metro", "true"},
            {"RC Car Pro!", "Metro", "true"},
            {"Taking Notes: In the Private Room", "Metro", "true", "8-bit", "Notes"},
            {"City Hall Lost & Found", "Metro", "true", "Chest"},
            {"Sewer Treasure", "Metro", "true"},
            {"Celebrating in the Streets!", "Metro", "true", "8-bit"},
            {"Pushing Through the Crowd", "Metro", "true", "Timer"},
            {"High Over the Crowd", "Metro", "true"},
            {"Rewiring the Neighborhood", "Metro", "true", "Outfit"},
            {"Off the Beaten Wire", "Metro", "true", "Outfit"},
            {"Moon Shards Under Siege", "Metro", "true"},
            {"Sharpshooting Under Siege", "Metro", "true"},
            {"Inside the Rotating Maze", "Metro", "true"},
            {"Outside the Rotating Maze", "Metro", "true"},
            {"Hanging from a High-Rise", "Metro", "true"},
            {"Vaulting from a High-Rise", "Metro", "true"},
            {"Bullet Billding", "Metro", "true"},
            {"One Man's Trash...", "Metro", "true"},
            {"Motor Scooter: Escape!", "Metro", "true"},
            {"Big Jump: Escape!", "Metro", "true"},
            {"Secret Path to New Donk City", "Metro", "true"},
            {"A Tourist in the Metro Kingdom!", "Metro", "true", "Tourist", "1"},
            {"Found with Metro Kingdom Art", "Lake", "false", "Art", "gp"},
            {"Bird Traveling in the City", "Metro", "false", "Bird"},
            {"Mario Signs His Name", "Metro", "false"},
            {"Surprise Clown!", "Metro", "false", "Outfit"},
            {"A Request from the Mayor", "Metro", "false"},
            {"Jammin' in the Metro Kingdom", "Metro", "false", "Music"},
            {"Sphynx in the City", "Metro", "false"},
            {"Free Parking: Leap of Faith", "Metro", "false"},
            {"Metro Kingdom Regular Cup", "Metro", "false", "kfr"},
            {"Hat-and-Seek: In the City", "Metro", "false", "Hat"},
            {"Powering Up the Power Plant", "Metro", "false"},
            {"Up on the Big Screen", "Metro", "false"},
            {"Down Inside the Big Screen", "Metro", "false", "8-bit"},
            {"Peach in the Metro Kingdom", "Metro", "false", "Peach"},
            {"Hanging Between Buildings", "Metro", "false"},
            {"Crossing Lines", "Metro", "false"},
            {"Out of a Crate in the City", "Metro", "false"},
            {"Bird Traveling the Park", "Metro", "false", "Bird"},
            {"Metro Kingdom Timer Challenge 3", "Metro", "false", "Timer"},
            {"Found in the Park! Good Dog!", "Metro", "false", "gp"},
            {"RC Car Champ!", "Metro", "false"},
            {"Metro Kingdom Master Cup", "Metro", "false", "kfr"},
            {"Hat-and-Seek: In the Crowd", "Metro", "false", "Hat"},
            {"Scaling Pitchblack Mountain", "Metro", "false"},
            {"Reaching Pitchblack Island", "Metro", "false", "gp"},
            {"Swinging Scaffolding: Jump!", "Metro", "false"},
            {"Swinging Scaffolding: Break!", "Metro", "false"},
            {"Motor Scooter Daredevil!", "Metro", "false"},
            {"Full-Throttle Scooting!", "Metro", "false", "Timer"},
            {"The Icicle Barrier", "Snow", "true"},
            {"The Ice Wall Barrier", "Snow", "true"},
            {"The Gusty Barrier", "Snow", "true"},
            {"The Snowy Mountain Barrier", "Snow", "true"},
            {"The Bound Bowl Grand Prix", "Snow", "true", "Story", "Multi"},
            {"Entrance to Shiveria", "Snow", "true"},
            {"Behind Snowy Mountain", "Snow", "true"},
            {"Shining in the Snow in Town", "Snow", "true", "gp"},
            {"Atop a Blustery Arch", "Snow", "true", "gp"},
            {"Caught Hopping in the Snow!", "Snow", "true", "Mips"},
            {"The Shiverian Treasure Chest", "Snow", "true", "Chest"},
            {"Treasure in the Ice Wall", "Snow", "true", "Chest"},
            {"Snow Kingdom Timer Challenge 1", "Snow", "true", "Timer"},
            {"Snow Kingdom Timer Challenge 2", "Snow", "true", "Timer"},
            {"Moon Shards in the Snow", "Snow", "true"},
            {"Taking Notes: Snow Path Dash", "Snow", "true", "Notes"},
            {"Fishing in the Glacier!", "Snow", "true", "Fishing"},
            {"Ice-Dodging Goomba Stack", "Snow", "true"},
            {"Captain Toad is Chilly!", "Snow", "true", "Toad"},
            {"I'm Not Cold!", "Snow", "true", "Outfit"},
            {"Shopping in Shiveria", "Snow", "true"},
            {"Walking on Ice!", "Snow", "true", "Trace"},
            {"Snowline Circuit Class S", "Snow", "true"},
            {"Dashing Over Cold Water!", "Snow", "true"},
            {"Dashing Above and Beyond!", "Snow", "true"},
            {"Jump 'n' Swim in the Freezing Water", "Snow", "true"},
            {"Freezing Water Near the Ceiling", "Snow", "true"},
            {"Blowing and Sliding", "Snow", "true"},
            {"Moon Shards in the Cold Room", "Snow", "true", "Outfit"},
            {"Slip Behind the Ice", "Snow", "true", "8-bit", "Outfit"},
            {"Spinning Above the Clouds", "Snow", "true"},
            {"High-Altitude Spinning", "Snow", "true"},
            {"Secret Path to Shiveria!", "Snow", "false"},
            {"Found with Snow Kingdom Art", "Lost", "false", "Art", "gp"},
            {"Snow Kingdom Regular Cup", "Snow", "false", "kfr"},
            {"Hat-and-Seek in the Snow", "Snow", "false", "Hat"},
            {"Peach in the Snow Kingdom", "Snow", "false", "Peach"},
            {"Shining on High", "Snow", "false"},
            {"Above the Freezing Fish Pond", "Snow", "false"},
            {"Ice Floe Swimming", "Snow", "false"},
            {"Icy Jump Challenge", "Snow", "false"},
            {"Forgotten in the Holding Room", "Snow", "false"},
            {"It Popped Out of the Ice", "Snow", "false", "gp"},
            {"Deep in the Cold, Cold Water", "Snow", "false", "gp"},
            {"Water Pooling in the Crevasse", "Snow", "false", "gp"},
            {"Squirming Under Ice", "Snow", "false", "gp"},
            {"Snow Kingdom Timer Challenge 3", "Snow", "false", "Timer"},
            {"Stacked-Up Ice Climb", "Snow", "false"},
            {"I Met a Snow Cheep Cheep!", "Snow", "false"},
            {"Even More Walking on Ice!", "Snow", "false", "Trace"},
            {"Snow Kingdom Master Cup", "Snow", "false", "kfr"},
            {"Iceburn Circuit Class A", "Snow", "false"},
            {"Iceburn Circuit Class S", "Snow", "false"},
            {"Running the Flower Road", "Snow", "false"},
            {"Looking Back on the Flower Road", "Snow", "false"},
            {"The Stone Pillar Seal", "Seaside", "true", "Story"},
            {"The Lighthouse Seal", "Seaside", "true", "Story"},
            {"The Hot Spring Seal", "Seaside", "true", "Story"},
            {"The Seal Above the Canyon", "Seaside", "true", "Story"},
            //Brigadier Mollusque-Lanceur III, Dauphin of Bubblaine
            {"The Glass is Half Full", "Seaside", "true", "Story", "Multi"},
            {"On the Cliff Overlooking the Beach", "Seaside", "true"},
            {"Ride the Jetstream", "Seaside", "true"},
            {"Ocean-Bottom Maze: Treasure", "Seaside", "true", "8-bit"},
            {"Ocean-Bottom Maze: Hidden Room", "Seaside", "true", "8-bit"},
            {"Underwater Highway Tunnel", "Seaside", "true"},
            {"Shh! It's a Shortcut!", "Seaside", "true"},
            {"Gap in the Ocean Trench", "Seaside", "true"},
            {"Slip Through the Nesting Spot", "Seaside", "true"},
            {"Merci, Dorrie!", "Seaside", "true"},
            {"Bonjour, Dorrie!", "Seaside", "true"},
            {"Under a Dangerous Ceiling", "Seaside", "true", "gp"},
            {"What the Waves Left Behind", "Seaside", "true", "gp"},
            {"The Back Canyon: Excavate!", "Seaside", "true", "gp"},
            {"Bubblaine Northern Reaches", "Seaside", "true", "gp"},
            {"Wriggling on the Sandy Bottom", "Seaside", "true", "gp"},
            {"Glass Palace Treasure Chest", "Seaside", "true", "Chest"},
            {"Treasure Trap Hidden in the Inlet", "Seaside", "true", "Chest"},
            {"Sea Gardening: Inlet Seed", "Seaside", "false", "Seed"},
            {"Sea Gardening: Canyon Seed", "Seaside", "false", "Seed"},
            {"Sea Gardening: Hot-Spring Seed", "Seaside", "false", "Seed"},
            {"Sea Gardening: Ocean Trench Seed", "Seaside", "false", "Seed"},
            {"Seaside Kingdom Timer Challenge 1", "Seaside", "true", "8-bit", "Timer"},
            {"Seaside Kingdom Timer Challenge 2", "Seaside", "true", "Timer"},
            {"Found on the Beach! Good Dog!", "Seaside", "true", "gp"},
            {"Moon Shards in the Sea", "Seaside", "true"},
            {"Taking Notes: Ocean Surface Dash", "Seaside", "true", "Notes"},
            {"Love by the Seaside", "Seaside", "true", "Goomba"},
            {"Lighthouse Leaper", "Seaside", "true"},
            {"Good Job, Captain Toad!", "Seaside", "true", "Toad"},
            {"Ocean Quiz: Good!", "Seaside", "true", "Sphynx"},
            {"Shopping in Bubblaine", "Seaside", "true"},
            {"Beach Vollyeball: Champ", "Seaside", "true", "Volleyball"},
            {"Beach Volleyball: Hero of the Beach!", "Seaside", "true", "Volleyball"},
            {"Looking Back in the Dark Waterway", "Seaside", "true"},
            {"The Sphynx's Underwater Vault", "Seaside", "true", "Chest"},
            {"A Rumble on the Seaside Floor", "Seaside", "true", "gp"},
            {"A Relaxing Dance", "Seaside", "true", "Outfit"},
            {"Wading in the Cloud Sea", "Seaside", "true"},
            {"Sunken Treasure in the Cloud Sea", "Seaside", "true", "Chest"},
            {"Fly Through the Narrow Valley", "Seaside", "true"},
            {"Treasure Chest in the Narrow Valley", "Seaside", "true", "Chest"},
            {"Hurry and Stretch", "Seaside", "true"},
            {"Stretch on the Side Path", "Seaside", "true"},
            {"Secret Path to Bubblaine!", "Seaside", "false"},
            {"Found with Seaside Kingdom Art", "Metro", "false", "Art", "gp"},
            {"Seaside Kingdom Regular Cup", "Seaside", "false", "kfr"},
            {"Peach in the Seaside Kingdom", "Seaside", "false", "Peach"},
            {"Above the Parasol: Catch!", "Seaside", "false"},
            {"What Shines Inside the Glass", "Seaside", "false"},
            {"A Fine Detail on the Glass", "Seaside", "false"},
            {"Underwater Highway West: Explore!", "Seaside", "false"},
            {"Underwater Highway East: Explore!", "Seaside", "false"},
            {"Rapid Ascent on Hot Spring Island", "Seaside", "false"},
            {"A Light Next to the Lighthouse", "Seaside", "false", "Cappy"},
            {"The Tall Rock Shelf in the Deep Ocean", "Seaside", "false", "Cappy"},
            {"At the Base of the Lighthouse", "Seaside", "false", "gp"},
            {"Bird Traveling Over the Ocean", "Seaside", "false", "Bird"},
            {"Caught Hopping at Glass Palace!", "Seaside", "false", "Mips"},
            {"Seaside Kingdom Timer Challenge 3", "Seaside", "false", "Timer"},
            {"Taking Notes: Ocean-Bottom Maze", "Seaside", "false", "8-bit", "Notes"},
            {"Taking Notes in the Sea", "Seaside", "false", "Notes"},
            {"Seaside Kingdom Master Cup", "Seaside", "false", "kfr"},
            {"Aim! Poke!", "Seaside", "false"},
            {"Poke! Roll!", "Seaside", "false"},
            {"The Spinning Maze: Search!", "Seaside", "false"},
            {"The Spinning Maze: Open!", "Seaside", "false", "Chest"},
            {"The Broodals Are After Some Cookin'", "Luncheon", "true", "Story"},
            {"Under the Cheese Rocks", "Luncheon", "true", "Story"},
            {"Big Pot on the Volcano: Dive In!", "Luncheon", "true", "Story", "Multi"},
            {"Climb Up the Cascading Magma", "Luncheon", "true", "Story"},
            {"Cookatiel Showdown!", "Luncheon", "true", "Story", "Multi"},
            {"Piled on the Salt", "Luncheon", "true"},
            {"Lurking in the Pillar's Shadow", "Luncheon", "true"},
            {"Atop the Jutting Crag", "Luncheon", "true"},
            {"Is This an Ingredient Too?!", "Luncheon", "true"},
            {"Atop a Column in a Row", "Luncheon", "true", "gp"},
            {"Surrounded by Tall Mountains", "Luncheon", "true", "gp"},
            {"Island of Salt Floating in the Lava", "Luncheon", "true", "gp"},
            {"Overlooking a Bunch of Ingredients", "Luncheon", "true", "gp"},
            {"Light the Lantern on the Small Island", "Luncheon", "true"},
            {"Golden Turnip Recipe 1", "Luncheon", "true"},
            {"Golden Turnip Recipe 2", "Luncheon", "true"},
            {"Golden Turnip Recipe 3", "Luncheon", "true"},
            {"Luncheon Kingdom Timer Challenge 1", "Luncheon", "true", "Timer"},
            {"Luncheon Kingdom Timer Challenge 2", "Luncheon", "true", "Timer"},
            {"Luncheon Kingdom Timer Challenge 3", "Luncheon", "true", "Timer"},
            {"Beneath the Rolling Vegetables", "Luncheon", "true", "8-bit"},
            {"All the Cracks Are Fixed", "Luncheon", "true", "gp"},
            {"Taking Notes: Swimming in Magma", "Luncheon", "true", "Notes"},
            {"Love Above the Lava", "Luncheon", "true", "Goomba"},
            {"Shopping in Mount Volbono", "Luncheon", "true"},
            {"Luncheon Kingdom Slots", "Luncheon", "true", "Slots"},
            {"A Strong Simmer", "Luncheon", "true", "Outfit"},
            {"An Extreme Simmer", "Luncheon", "true", "Outfit"},
            {"Alcove Behind the Pillars of Magma", "Luncheon", "true"},
            {"Treasure Beneath the Cheese Rocks", "Luncheon", "true", "gp"},
            {"Light the Two Flames", "Luncheon", "true"},
            {"Light the Far-Off Lanterns", "Luncheon", "true"},
            {"Bon Appetit, Captain Toad!", "Luncheon", "true", "Toad"},
            {"The Treasure Chest in the Veggies", "Luncheon", "true", "Chest"},
            {"Caught Hopping at the Volcano!", "Luncheon", "true", "Mips"},
            {"Taking Notes: Big Pot Swim", "Luncheon", "true", "Notes"},
            {"Magma Swamp: Floating and Sinking", "Luncheon", "true"},
            {"Corner of the Magma Swamp", "Luncheon", "true"},
            {"Magma Narrow Path", "Luncheon", "true"},
            {"Crossing to the Magma", "Luncheon", "true"},
            {"Fork Flickin' to the Summit", "Luncheon", "true"},
            {"Fork Flickin' Detour", "Luncheon", "true"},
            {"Excavate 'n' Search the Cheese Rocks", "Luncheon", "true"},
            {"Climb the Cheese Rocks", "Luncheon", "true"},
            {"Spinning Athletics End Goal", "Luncheon", "true"},
            {"Taking Notes: Spinning Athletics", "Luncheon", "true", "Notes"},
            {"Secret Path to Mount Volbono!", "Luncheon", "true"},
            {"A Tourist in the Luncheon Kingdom!", "Luncheon", "false", "Tourist", "3"},
            {"Found with Luncheon Kingdom Art", "Seaside", "false", "Art", "gp"},
            {"The Rooftop Lantern", "Luncheon", "false"},
            {"Jammin' in the Luncheon Kingdom", "Luncheon", "false", "Music"},
            {"Mechanic: Repairs Complete!", "Luncheon", "false", "Outfit"},
            {"Diving from the Big Pot!", "Luncheon", "false"},
            {"Hat-and-Seek: Among the Food", "Luncheon", "false", "Hat"},
            {"Luncheon Kingdom: Regular Cup", "Luncheon", "false", "kfr"},
            {"Peach in the Luncheon Kingdom", "Luncheon", "false", "Peach"},
            {"From Inside a Bright Stone", "Luncheon", "false", "gp"},
            {"Under the Meat Plateau", "Luncheon", "false"},
            {"On Top of a Tall, Tall Roof", "Luncheon", "false"},
            {"From a Crack in the Hard Ground", "Luncheon", "false", "gp"},
            {"By the Cannon Pointed at the Big Pot", "Luncheon", "false", "gp"},
            {"Luncheon Kingdom: Master Cup", "Luncheon", "false", "kfr"},
            {"Stepping over the Gears", "Luncheon", "false"},
            {"Lanterns on the Gear Steps", "Luncheon", "false"},
            {"Volcano Cave Cruisin'", "Luncheon", "false"},
            {"Volcano Cave and Mysterious Clouds", "Luncheon", "false"},
            {"Treasure of the Lava Islands", "Luncheon", "false"},
            {"Flying Over the Lava Islands", "Luncheon", "false"},
            {"Battle with the Lord of Lightning!", "Ruined", "true", "Story", "Multi"},
            {"In the Ancient Treasure Chest", "Ruined", "true", "Chest"},
            {"Roulette Tower: Climbed", "Ruined", "true"},
            {"Roulette Tower: Stopped", "Ruined", "true", "8-bit"},
            {"Peach in the Ruined Kingdom", "Ruined", "false", "Peach"},
            {"Caught on a Big Horn", "Ruined", "false", "Cappy"},
            {"Upon the Broken Arch", "Ruined", "false", "gp"},
            {"Rolling Rock on the Battlefield", "Ruined", "false"},
            {"Charging Through an Army", "Ruined", "false"},
            {"The Mummy Army's Curse", "Ruined", "false"},
            {"Infiltrate Bowser's Castle!", "Bowser's", "true", "Story"},
            {"Smart Bombing", "Bowser's", "true", "Story"},
            {"Big Broodal Battle", "Bowser's", "true", "Story"},
            {"Showdown at Bowser's Castle", "Bowser's", "true", "Story", "Multi"},
            {"Behind the Big Wall", "Bowser's", "true"},
            {"Treasure Inside the Turret", "Bowser's", "true"},
            {"From the Side Above the Castle Gate", "Bowser's", "true"},
            {"Sunken Treasure in the Moat", "Bowser's", "true"},
            {"Past the Moving Wall", "Bowser's", "true"},
            {"Above the Poison Swamp", "Bowser's", "true"},
            {"Knocking Down the Nice Frame", "Bowser's", "true"},
            {"Caught on the Iron Fence", "Bowser's", "true", "Cappy"},
            {"On the Giant Bowser Statue's Nose", "Bowser's", "true", "gp"},
            {"Inside a Block in the Castle", "Bowser's", "true"},
            {"Caught Hopping at Bowser's Castle!", "Bowser's", "true", "Mips"},
            {"Exterminate the Ogres!", "Bowser's", "true"},
            {"Bowser's Kingdom Timer Challenge 1", "Bowser's", "true", "Timer"},
            {"Taking Notes: Between Spinies", "Bowser's", "true", "Notes"},
            {"Stack Up Above the Wall", "Bowser's", "true"},
            {"Hidden Corridor Under the Floor", "Bowser's", "true"},
            {"Poking Your Nose in the Plaster Wall", "Bowser's", "true"},
            {"Poking the Turret Wall", "Bowser's", "true"},
            {"Poking Your Nose by the Great Gate", "Bowser's", "true"},
            {"Jizo All in a Row", "Bowser's", "true"},
            {"Underground Jizo", "Bowser's", "true"},
            {"Found Behind Bars!", "Bowser's", "true"},
            {"Fishing(?) in Bowser's Castle", "Bowser's", "true", "Fishing"},
            {"Good to See You, Captain Toad!", "Bowser's", "true", "Toad"},
            {"Shopping at Bowser's Castle", "Bowser's", "true"},
            {"Bowser's Castle Treasure Vault", "Bowser's", "true", "Chest"},
            {"Scene of Crossing the Poison Swamp", "Bowser's", "true", "8-bit", "Outfit"},
            {"Taking Notes: In the Folding Screen", "Bowser's", "true", "8-bit", "Notes", "Outfit"},
            {"On Top of the Spinning Tower", "Bowser's", "true"},
            {"Down and Up the Spinning Tower", "Bowser's", "true"},
            {"Jizo's Big Adventure", "Bowser's", "true"},
            {"Jizo and the Hidden Room", "Bowser's", "true"},
            {"Dashing Above the Clouds", "Bowser's", "true"},
            {"Dashing Through the Clouds", "Bowser's", "true"},
            {"Sphynx Over Bowser's Castle", "Bowser's", "false"},
            {"I Met a Pokio!", "Bowser's", "false"},
            {"Bowser's Kingdom Regular Cup", "Bowser's", "false", "kfr"},
            {"A Rumble Under the Arena Floor", "Bowser's", "false", "gp"},
            {"Secret Path to Bowser's Castle", "Bowser's", "false"},
            {"Peach in Bowser's Kingdom", "Bowser's", "false", "Peach"},
            {"Found with Bowser's Kingdom Art", "Sand", "false", "Art", "gp"},
            {"Behind the Tall Wall: Poke, Poke!", "Bowser's", "false"},
            {"From Crates in the Moat", "Bowser's", "false"},
            {"Caught on the Giant Horn", "Bowser's", "false", "Cappy"},
            {"Inside a Block at the Gate", "Bowser's", "false"},
            {"Small Bird in Bowser's Castle", "Bowser's", "false", "Bird"},
            {"Invader in Bowser's Castle", "Bowser's", "false"},
            {"Jumping from Flag to Flag", "Bowser's", "false"},
            {"Bowser's Kingdom Timer Challenge 2", "Bowser's", "false", "Timer"},
            {"Taking Notes: On the Wall", "Bowser's", "false", "Notes"},
            {"Taking Notes with a Spinning Throw", "Bowser's", "false", "Notes"},
            {"Third Courtyard Outskirts", "Bowser's", "false"},
            {"Stone Wall Circuit", "Bowser's", "false"},
            {"Bowser's Kingdom Master Cup", "Bowser's", "false", "kfr"},
            {"Searching Hexagon Tower", "Bowser's", "false"},
            {"Center of Hexagon Tower", "Bowser's", "false"},
            {"Climb the Wooden Tower", "Bowser's", "false"},
            {"Poke the Wooden Tower", "Bowser's", "false"},
            {"Shining Above the Moon", "Moon", "true"},
            {"Along the Cliff Face", "Moon", "true", "8-bit"},
            {"The Tip of a White Spire", "Moon", "true", "Cappy"},
            {"Rolling Rock on the Moon", "Moon", "true"},
            {"Caught Hopping on the Moon!", "Moon", "true", "Mips"},
            {"Cliffside Treasure Chest", "Moon", "true", "Chest"},
            {"Moon Kingdom Timer Challenge 1", "Moon", "true", "Timer"},
            {"Taking Notes: On the Moon's Surface", "Moon", "true", "Notes"},
            {"Under the Bowser Statue", "Moon", "true"},
            {"In a Hole in the Magma", "Moon", "true"},
            {"Around the Barrier Wall", "Moon", "true"},
            {"On Top of the Cannon", "Moon", "true", "gp"},
            {"Fly to the Treasure Chest and Back", "Moon", "true", "Chest"},
            {"Up in the Rafters", "Moon", "true"},
            {"Sneaking Around in the Crater", "Moon", "false"},
            {"Found on the Moon, Good Dog!", "Moon", "false", "gp"},
            {"Moon Shards on the Moon", "Moon", "false"},
            {"Moon Quiz: Amazing!", "Moon", "false", "Sphynx"},
            {"Thanks, Captain Toad!", "Moon", "false", "Toad"},
            {"Shopping in Honeylune Ridge", "Moon", "false"},
            {"Walking on the Moon!", "Moon", "false", "Trace"},
            {"Moon Kingdom Regular Cup", "Moon", "false", "kfr"},
            {"Doctor in the House", "Moon", "false", "Outfit"},
            {"Sphynx's Hidden Vault", "Moon", "false", "Chest"},
            {"A Tourist in the Moon Kingdom!", "Moon", "false", "Tourist", "4"},
            {"Peach in the Moon Kingdom", "Moon", "false", "Peach"},
            {"Found with Moon Kingdom Art", "Wooded", "false", "Art", "gp"},
            {"Mysterious Flying Object", "Moon", "false", "Bird"},
            {"Hidden on the Side of the Cliff", "Moon", "false"},
            {"Jumping High as a Frog", "Moon", "false"},
            {"Moon Kingdom Timer Challenge 2", "Moon", "false", "Timer"},
            {"Walking on the Moon: Again!", "Moon", "false", "Trace"},
            {"Moon Kingdom Master Cup", "Moon", "false", "kfr"},
            {"Taking Notes: In Low Gravity", "Moon", "false", "8-bit", "Notes"},
            {"Center of the Galaxy", "Moon", "false", "8-bit"},
            {"Edge of the Galaxy", "Moon", "false", "8-bit"},
            {"Navigating Giant Swings", "Moon", "false"},
            {"A Swing on Top of a Swing", "Moon", "false"},
            {"Perched on the Castle Roof", "Mushroom", "true"},
            {"Pops Out of the Tail", "Mushroom", "true", "Cappy"},
            {"Caught Hopping at Peach's Castle!", "Mushroom", "true", "Mips"},
            {"Gardening for Toad: Garden Seed", "Mushroom", "true", "Seed"},
            {"Gardening for Toad: Field Seed", "Mushroom", "true", "Seed"},
            {"Gardening for Toad: Pasture Seed", "Mushroom", "true", "Seed"},
            {"Gardening for Toad: Lake Seed", "Mushroom", "true", "Seed"},
            {"Grow a Flower Garden", "Mushroom", "true"},
            {"Mushroom Kingdom Timer Challenge", "Mushroom", "true", "Timer"},
            {"Found at Peach's Castle! Good Dog!", "Mushroom", "true", "gp"},
            {"Taking Notes: Around the Well", "Mushroom", "true", "Notes"},
            {"Herding Sheep at Peach's Castle!", "Mushroom", "true", "Sheep"},
            {"Gobbling Fruit with Yoshi", "Mushroom", "true", "Yoshi", "1"},
            {"Yoshi's Second Helping!", "Mushroom", "true", "Yoshi", "2"},
            {"Yoshi's All Filled Up!", "Mushroom", "true", "Yoshi", "3"},
            {"Love at Peach's Castle", "Mushroom", "true", "Goomba"},
            {"Toad Defender", "Mushroom", "true"},
            {"Forever Onward, Captain Toad!", "Mushroom", "true", "Toad"},
            {"Jammin' in the Mushroom Kingdom", "Mushroom", "true", "Music"},
            {"Shopping Near Peach's Castle", "Mushroom", "true"},
            {"Mushroom Kingdom Regular Cup", "Mushroom", "true", "kfr"},
            {"Mushroom Kingdom Master Cup", "Mushroom", "true", "kfr"},
            {"Picture Match: Basically Mario", "Mushroom", "true"},
            {"Picture Match: A Stellar Mario", "Mushroom", "true"},
            {"Light from the Ceiling", "Mushroom", "true"},
            {"Loose-Tile Trackdown", "Mushroom", "true", "gp"},
            {"Totally Classic!", "Mushroom", "true", "Outfit"},
            {"Courtyard Chest Trap", "Mushroom", "true", "Chest", "Outfit"},
            {"Yoshi's Feast in the Sea of Clouds", "Mushroom", "true"},
            {"Sunken Star in the Sea of Clouds", "Mushroom", "true"},
            {"Secret 2D Treasure", "Mushroom", "true", "8-bit"},
            {"2D Boost from Bullet Bill", "Mushroom", "true", "8-bit"},
            {"Tussle in Tostarena: Rematch", "Mushroom", "true", "Multi"},
            {"Struggle in Steam Gardens: Rematch", "Mushroom", "true", "Multi"},
            {"Dust-Up in New Donk City: Rematch", "Mushroom", "true", "Multi"},
            {"Battle in Bubblaine: Rematch", "Mushroom", "true", "Multi"},
            {"Blowup at Mount Volbono: Rematch", "Mushroom", "true", "Multi"},
            {"Rumble in Crumbleden: Rematch", "Mushroom", "true", "Multi"},
            {"Secret Path to Peach's Castle!", "Mushroom", "true"},
            {"A Tourist in the Mushroom Kingdom!", "Mushroom", "true", "Tourist", "5"},
            {"Found with Mushroom Kingdom Art", "Cap", "false", "Art", "gp"},
            {"Hat-and-Seek: Mushroom Kingdom", "Mushroom", "false", "Hat"},
            {"Princess Peach, Home Again!", "Mushroom", "false", "Peach"},
            {"Rescue Princess Peach", "Achievements", "1", "Win", "1"},
            {"Achieve World Peace", "Achievements", "1", "Peace", "1"},
            {"Power Moon Knight", "Achievements", "1", "Moons", "100"},
            {"Power Moon Wizard", "Achievements", "2", "Moons", "300"},
            {"Regional Coin Shopper", "Achievements", "2", "Purples", "13"},
            {"Flat Moon Finder", "Achievements", "1", "8-bit", "10"},
            {"Flat Moon Fanatic", "Achievements", "2", "8-bit", "25"},
            {"Treasure Chest Hunter", "Achievements", "1", "Chest", "15"},
            {"Super Treasure Chest Hunter", "Achievements", "2", "Chest", "25"},
            {"Note-Collecting World Tour", "Achievements", "1", "Notes", "5"},
            {"Note-Collecting Space Tour", "Achievements", "2", "Notes", "20"},
            {"Timer Challenge Amateur", "Achievements", "1", "Timer", "10"},
            {"Timer Challenge Professional", "Achievements", "2", "Timer", "25"},
            {"Captain Toad Meeter", "Achievements", "1", "Toad", "5"},
            {"Captain Toad Greeter", "Achievements", "2", "Toad", "10"},
            {"Touring with Princess Peach", "Achievements", "1", "Peach", "5"},
            {"Globe-Trotting with Princess Peach", "Achievements", "2", "Peach", "10"},
            {"Master Sheep Herder", "Achievements", "1", "Sheep", "4"},
            {"Gaga for Goombette", "Achievements", "1", "Goomba", "5"},
            {"Lakitu Fishing Trip", "Achievements", "1", "Fishing", "3"},
            {"Flower-Growing Guru", "Achievements", "1", "Seed", "5"},
            {"Flower-Growing Sage", "Achievements", "2", "Seed", "10"},
            {"Running with Rabbits", "Achievements", "1", "Mips", "5"},
            {"Racing with Rabbits", "Achievements", "2", "Mips", "10"},
            {"Ground Pound Instructor", "Achievements", "1", "gp", "15"},
            {"Ground Pound Professor", "Achievements", "2", "gp", "45"},
            {"Rad Hatter", "Achievements", "1", "Cappy", "3"},
            {"Super Rad Hatter", "Achievements", "2", "Cappy", "10"},
            {"Traveling-Bird Herder", "Achievements", "1", "Bird", "5"},
            {"Wearing It Well!", "Achievements", "1", "Outfit", "3"},
            {"Wearing It Great!", "Achievements", "2", "Outfit", "8"},
            {"Wearing It Perfect!", "Achievements", "3", "Outfit", "15"},
            {"Hat-Seeking Missile", "Achievements", "1", "Hat", "5"},
            {"Music Maestro", "Achievements", "1", "Music", "5"},
            {"Art Enthusiast", "Achievements", "1", "Art", "5"},
            {"Art Investigator", "Achievements", "2", "Art", "15"},
            {"Slots Machine", "Achievements", "1", "Slots", "3"},
            {"Koopa Freerunning MVP", "Achievements", "1", "kfr", "10"},
            {"Koopa Freerunning Hall of Famer", "Achievements", "2", "kfr", "22"},
            {"Supernaturally Sure-Footed", "Achievements", "1", "Trace", "5"},
            {"Quizmaster", "Achievements", "1", "Sphynx", "3"},
            {"Souvenir Sampler", "Achievements", "1", "Souvenir", "10"},
            {"Souvenir Sleuth", "Achievements", "2", "Souvenir", "20"},
            {"Souvenir Savant", "Achievements", "3", "Souvenir", "40"},
            {"Capturing Novice", "Achievements", "1", "Capture", "20"},
            {"Capturing Apprentice", "Achievements", "2", "Capture", "35"},
            {"Capturing Master", "Achievements", "3", "Capture", "45"},
            {"Hat Maven", "Achievements", "1", "Hats", "15"},
            {"Hat Icon", "Achievements", "2", "Hats", "35"},
            {"Fashion Maven", "Achievements", "1", "Outfits", "15"},
            {"Fashion Icon", "Achievements", "2", "Outfits", "35"},
            {"Moon Rock Liberator", "Achievements", "1", "Moon Rocks", "14"},
            {"World Warper", "Achievements", "1", "Paintings", "10"},
            {"Checkpoint Flagger", "Achievements", "1", "CPs", "40"},
            {"Checkpoint Flag Enthusiast", "Achievements", "2", "CPs", "80"},
            {"Loaded with Coins", "Achievements", "1", "Coins", "1000"},
            {"Rolling in Coins", "Achievements", "2", "Coins", "5000"},
            {"Arrival at Rabbit Ridge!", "Dark Side", "true", "Multi"},
            {"Captain Toad on the Dark Side!", "Dark Side", "true", "Toad"},
            {"Breakdown Road: Hurry!", "Dark Side", "true"},
            {"Breakdown Road: Final Challenge!", "Dark Side", "true"},
            {"Invisible Road: Rush!", "Dark Side", "true"},
            {"Invisible Road: Secret!", "Dark Side", "true", "Chest"},
            {"Vanishing Road Rush", "Dark Side", "true"},
            {"Vanishing Road Challenge", "Dark Side", "true"},
            {"Yoshi Under Siege", "Dark Side", "true"},
            {"Fruit Feast Under Siege", "Dark Side", "true"},
            {"Yoshi on the Sinking Island", "Dark Side", "true"},
            {"Fruit Feast on the Sinking Island", "Dark Side", "true"},
            {"Yoshi's Magma Swamp", "Dark Side", "true"},
            {"Fruit Feast in the Magma Swamp!", "Dark Side", "true"},
            {"Found with Dark Side Art 1", "Cascade", "false", "Art", "gp"},
            {"Found with Dark Side Art 2", "Metro", "false", "Art", "gp"},
            {"Found with Dark Side Art 3", "Mushroom", "false", "Art", "gp"},
            {"Found with Dark Side Art 4", "Cloud", "false", "Art", "gp"},
            {"Found with Dark Side Art 5", "Snow", "false", "Art", "gp"},
            {"Found with Dark Side Art 6", "Seaside", "false", "Art", "gp"},
            {"Found with Dark Side Art 7", "Lost", "false", "Art", "gp"},
            {"Found with Dark Side Art 8", "Luncheon", "false", "Art", "gp"},
            {"Found with Dark Side Art 9", "Lake", "false", "Art", "gp"},
            {"Found with Dark Side Art 10", "Ruined", "false", "Art", "gp"},
    };

    static int indexOfMoon(Moon moon){
        for (int i = 0; i < Lists.moons.length; i++) {
            if(Lists.moons[i][0].equals(moon.getName()))
                return i;
        }
        return -1;
    }

    /**
     * When the moon list is updated to handle first visit / revisit / post game / moon rock this will be unnecessary
     */
    static final String[] PG_NOT_MOON_ROCK = {"Frog-Jumping Above the Fog",
            "Frog-Jumping From the Top Deck",
            "Cap Kingdom Timer Challenge 1",
            "Good Evening, Captain Toad",
            "Shopping in Bonneton",
            "Skimming the Poison Tide",
            "Slipping Through the Poison Tide",
            "Push-Block Peril",
            "Hidden Among the Push-Blocks",
            "Searching the Frog Pond",
            "Secrets of the Frog Pond",
            "The Forgotten Treasure",
            "Taxi Flying Through Bonneton",
            "Bonneter Blockade",
            "Cap Kingdom Regular Cup",
            "Peach in the Cap Kingdom",
            "Found with Cap Kingdom Art",
            "Secret Path to Fossil Falls!",
            "A Tourist in the Cascade Kingdom",
            "Rolling Rock by the Falls",
            "Peach in the Cascade Kingdom",
            "Cascade Kingdom Regular Cup",
            "Caveman Cave-Fan",
            "Sphynx Traveling to the Waterfall",
            "Desert Gardening: Plaza Seed",
            "Desert Gardening: Ruins Seed",
            "Desert Gardening: Seed on the Cliff",
            "Secret Path to Tostarena!",
            "Found with Sand Kingdom Art",
            "Jammin' in the Sand Kingdom",
            "Hat-and-Seek: In the Sand",
            "Sand Kingdom Regular Cup",
            "Binding Band Returned",
            "'Round-the-World Tourist",
            "Peach in the Sand Kingdom",
            "Lake Gardening: Spiky Passage Seed",
            "Secret Path to Lake Lamode",
            "Found with Lake Kingdom Art",
            "Taxi Flying Through Lake Lamode",
            "That Trendy \"Pirate\" Look",
            "Space is \"In\" Right Now",
            "That \"Old West\" Style",
            "Lake Kingdom Regular Cup",
            "Peach in the Lake Kingdom",
            "Secret Path to the Steam Gardens!",
            "Found with Wooded Kingdom Art",
            "Swing Around Secret Flower Field",
            "Jammin' in the Wooded Kingdom",
            "Wooded Kingdom Regular Cup",
            "Peach in the Wooded Kingdom",
            "Picture Match: Basically a Goomba",
            "Peach in the Cloud Kingdom",
            "Caught Hopping in the Jungle!",
            "Taxi Flying Through Forgotten Isle",
            "I Met a Tropical Wiggler!",
            "Lost Kingdom Regular Cup",
            "Peach in the Lost Kingdom",
            "City Gardening: Building Planter",
            "City Gardening: Plaza Planter",
            "City Gardening: Rooftop Planter",
            "Found with Metro Kingdom Art",
            "Bird Traveling in the City",
            "Mario Signs His Name",
            "Surprise Clown!",
            "A Request from the Mayor",
            "Jammin' in the Metro Kingdom",
            "Sphynx in the City",
            "Free Parking: Leap of Faith",
            "Metro Kingdom Regular Cup",
            "Hat-and-Seek: In the City",
            "Powering Up the Power Plant",
            "Up on the Big Screen",
            "Down Inside the Big Screen",
            "Peach in the Metro Kingdom",
            "Secret Path to Shiveria!",
            "Found with Snow Kingdom Art",
            "Snow Kingdom Regular Cup",
            "Hat-and-Seek in the Snow",
            "Peach in the Snow Kingdom",
            "Sea Gardening: Inlet Seed",
            "Sea Gardening: Canyon Seed",
            "Sea Gardening: Hot-Spring Seed",
            "Sea Gardening: Ocean Trench Seed",
            "Secret Path to Bubblaine!",
            "Found with Seaside Kingdom Art",
            "Seaside Kingdom Regular Cup",
            "Peach in the Seaside Kingdom",
            "A Tourist in the Luncheon Kingdom!",
            "Found with Luncheon Kingdom Art",
            "The Rooftop Lantern",
            "Jammin' in the Luncheon Kingdom",
            "Mechanic: Repairs Complete!",
            "Diving from the Big Pot!",
            "Hat-and-Seek: Among the Food",
            "Luncheon Kingdom: Regular Cup",
            "Peach in the Luncheon Kingdom",
            "Peach in the Ruined Kingdom",
            "Sphynx Over Bowser's Castle",
            "I Met a Pokio!",
            "Bowser's Kingdom Regular Cup",
            "A Rumble Under the Arena Floor",
            "Secret Path to Bowser's Castle!",
            "Peach in Bowser's Kingdom",
            "Found with Bowser's Kingdom Art",
            "Sneaking Around in the Crater",
            "Found on the Moon, Good Dog!",
            "Moon Shards on the Moon",
            "Moon Quiz: Amazing!",
            "Thanks, Captain Toad!",
            "Shopping in Honeylune Ridge",
            "Walking on the Moon!",
            "Moon Kingdom Regular Cup",
            "Doctor in the House",
            "Sphynx's Hidden Vault",
            "A Tourist in the Moon Kingdom!",
            "Peach in the Moon Kingdom",
            "Found with Moon Kingdom Art"
    };

    static final String[] ACHIEVEMENT_TAGS = {"8-bit", "Art", "Bird", "Cappy", "Chest",
            "Fishing", "Goomba", "gp", "Hat", "kfr", "Mips", "Music", "Notes", "Outfit",
            "Peach", "Seed", "Sheep", "Slots", "Sphynx", "Timer", "Toad"};

    static final int[][] ACHIEVEMENT_LEVELS = {{10, 25}, //8-bit
            {5,15}, //art
            {5}, //bird
            {3, 10}, //cappy
            {15, 25}, //chest
            {3}, //fishing
            {5}, //goomba
            {15, 45}, //gp
            {5}, //hat
            {10,22}, //kfr
            {5,10}, //mips
            {5}, //music
            {5,20}, //notes
            {3,8,15}, //outfit
            {5,10}, //peach
            {5,10}, //seed
            {4}, //sheep
            {3}, //slots
            {3}, //sphynx
            {10,25}, //timer
            {5, 10} //Toad
    };

    static final String[][] kingdomFirstVisitReq = {
            {"Cap", "0"},
            {"Cascade", "5"},
            {"Sand", "16"},
            {"Lake", "8"},
            {"Wooded", "16"},
            {"Cloud", "0"},
            {"Lost", "10"},
            {"Metro", "20"},
            {"Snow", "10"},
            {"Seaside", "10"},
            {"Luncheon", "18"},
            {"Ruined", "3"},
            {"Bowser's", "8"},
            {"Moon", "0"},
            {"Mushroom", "0"},
            {"Dark Side", "0"}
    };
}